### ISSUE TITLE
Editable. Leave. Announcement.

### ISSUE THREAD

**Issue by austinhuang0131** [lapzbot/feature-requests#24]
Since the join announcement is editable, the leave announcement should also be editable, right?
~~Did I write too little?~~

**Comment by lap00zza** [comment]
It is indeed needed. Will push the changes ASAP.

**Comment by lap00zza** [comment]
Added as of now. You can use `?set_leave MESSAGE` to set custom leave messages. This closes it. Will add this to Web Console in the near future.
